config/routes.rb
Lawrenson::Application.routes.draw do
  devise_for :users

  resources :sports
  resources :teams
  resources :competitions do
  	resources :games
  end
  resources :games, :only => [:create, :update]
  resources :leagues
  resources :roles

  root :to => "leagues#index"

end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :name, :competition_ids
  
  has_and_belongs_to_many :competitions
  has_many :league_members
  has_many :members, :through => :league_members, :source => :user
  
  before_validation :add_user_as_owner
  
  # Should validate that a new league is created with an owner
  
  def owner
  	ownerRole = Role.where('role = ?', 'owner')[0]
  	ownerRow = LeagueMember.where('league_id = ? AND role_id = ?', id, ownerRole.id)[0]
	owner = User.find(ownerRow.user_id)
  end
  
  private
  
  def add_user_as_owner
  	# Create a LeagueMember for current user and give them the owner role
  end
  
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league = League.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.json
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.json
  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<h1>Listing leagues</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leagues.each do |league| %>
  <tr>
    <td><%= link_to 'Show', league %></td>
    <td><%= link_to 'Edit', edit_league_path(league) %></td>
    <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>