config/routes.rb
Lawrenson::Application.routes.draw do
  devise_for :users

  resources :sports
  resources :teams
  resources :competitions do
  	resources :games
  end
  resources :games, :only => [:create, :update]
  resources :leagues
  resources :roles

  root :to => "leagues#index"

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :name
  
  has_many :team
  has_many :competition
  
  validates :name, :presence => true
  validates :name, :uniqueness => true
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sports }
    end
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
    @sport = Sport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /sports/new
  # GET /sports/new.json
  def new
    @sport = Sport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /sports/1/edit
  def edit
    @sport = Sport.find(params[:id])
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(params[:sport])

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render json: @sport, status: :created, location: @sport }
      else
        format.html { render action: "new" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sports/1
  # PUT /sports/1.json
  def update
    @sport = Sport.find(params[:id])

    respond_to do |format|
      if @sport.update_attributes(params[:sport])
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to sports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @sports.each do |sport| %>
  <tr>
  	<td><%= sport.name %></td>
    <td><%= link_to 'Show', sport %></td>
    <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
    <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<%= @sport.name %>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>