config/routes.rb
Lawrenson::Application.routes.draw do
  devise_for :users

  resources :sports
  resources :teams
  resources :competitions do
  	resources :games
  end
  resources :games, :only => [:create, :update]
  resources :leagues
  resources :roles

  root :to => "leagues#index"

end

app/models/competition.rb
class Competition < ActiveRecord::Base
  attr_accessible :active, :end_date, :name, :sport_id, :start_date
  
  belongs_to :sport
  has_many :games
  has_and_belongs_to_many :leagues
  
  validates :name, :sport_id, :presence => true
  validates :sport_id, :existence => true
  validates :end_date, :timeliness => {:after => :start_date, :allow_blank => true, :after_message => "must be after start_date"}	

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competitions }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @competition = Competition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/new
  # GET /competitions/new.json
  def new
    @competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/1/edit
  def edit
    @competition = Competition.find(params[:id])
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(params[:competition])

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render json: @competition, status: :created, location: @competition }
      else
        format.html { render action: "new" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competitions/1
  # PUT /competitions/1.json
  def update
    @competition = Competition.find(params[:id])

    respond_to do |format|
      if @competition.update_attributes(params[:competition])
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.label Sport %>
	<%= f.collection_select(:sport_id, Sport.all, :id, :name) %>
  </div>
  <div class="field">
	<%= f.label :start_date %>
	<%= f.date_select(:start_date) %>
  </div>
  <div class="field">
	<%= f.label :end_date %>
	<%= f.date_select(:end_date) %>
  </div>
  <div class="field">
	<%= f.label :active %>
	<%= f.check_box(:active) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Listing competitions</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @competitions.each do |competition| %>
  <tr>
  	<td><%= competition.name %></td>
    <td><%= link_to 'Show', competition %></td>
    <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
    <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<%= @competition.name %>
<%= @competition.sport.name %>
<%= @competition.start_date %>
<%= @competition.end_date %>
<%= @competition.active %>

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>

<div id="games">
	<%= link_to 'Add Game', new_competition_game_path(@competition) %>
	<ul>
	  <% @competition.games.each do |game| %>
		<li>
		  <%= game.date %>
		  <%= game.home_team.name %>
		  (<%= game.home_score %>)
		  :
		  <%= game.away_team.name %>
		  (<%= game.away_score %>) 
		  <%= link_to 'Edit', edit_competition_game_path(@competition, game) %>
		</li>
      <% end %>
	</ul>
</div>