config/routes.rb
Lawrenson::Application.routes.draw do
  devise_for :users

  resources :sports
  resources :teams
  resources :competitions do
  	resources :games
  end
  resources :games, :only => [:create, :update]
  resources :leagues
  resources :roles

  root :to => "leagues#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # Owned by devise
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Owned by app
  attr_accessible :first_name, :last_name
  
  has_many :predictions
  has_many :league_members
  has_many :leagues, :through => :league_members
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
  </div>
  <div class="field">
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
  </div>
  <div class="field">
	<%= f.label :email %>
	<%= f.email_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
  	<td><%= user.first_name %></td>
	<td><%= user.last_name %></td>
	<td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.first_name + ' ' + @user.last_name %></h1>
<%= @user.email %>

<div>
	<h2>Leagues</h2>
	<%= link_to 'Add', new_league_path %>
	<ul>
	  <% @user.leagues.each do |league| %>
		<li>
		  <%= league.name %>
		  <%= link_to 'View', show_league_path(league) %>
		</li>
      <% end %>
	</ul>
</div>

<div>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>